version: "3"

services:
  web:
    build:
      context: .
      target: bpe-be
    container_name: bpe-be
    image: golang:alpine3.16
    volumes:
      - ./:/go/src/bpe
    ports:
      - "8080:8080"
    working_dir: /go/src/bpe
    command: sh -c "go mod tidy && go run main.go"
    # docker exec -it bpe-be bash
    # go mod tidy && go run main.go
    depends_on:
      - db
    restart: unless-stopped
    tty: true
  db:
    container_name: bpe-db
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bpe
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - postgre:/var/lib/postgresql/data
      - ./postgre-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    # command: /bin/bash
    # docker exec -it bpe-db /bin/bash
    # psql --username bpe
    # donen 
volumes:
  postgre:
    name: postgre
    driver: local
